logging:
  level:
    root: info
    com.tistory.jaimemin.searcher: debug

spring:
  application:
    name: initial-searcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: user
    password: password
    hikari:
      maximum-pool-size: 20
server:
  port: 8081
